### ISSUE TITLE
Add lf line ending preference to .editorconfig.

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-server#101]
# Requirements

- [ ] Add the thing that does the stuff

# Dependencies

- None

**Comment by ermish** [comment]
@ann-kilzer wish I thought of this sooner, but this is where editorconfig can help auto set the preference! I think this combined with the gitattributes and we'll be golden ✨✨

**Comment by ann-kilzer** [comment]
??
I already did that: https://github.com/ourjapanlife/findadoc-server/blob/8ae6e5fb276202993bb35226efa6c4e43dbac37c/.editorconfig#L7

**Comment by ermish** [comment]
Oh lawl! @ann-kilzer  That's what I get for trying to do code things while my hair is being colored 💇‍♂️
