### ISSUE TITLE
Digital Ocean environment is breaking with the latest changes

### ISSUE THREAD

**Issue by theyokohamalife** [ourjapanlife/findadoc-server#158]
# Error message

"message": "\nInvalid `client_1.default.degree.findMany()` invocation in\n/workspace/dist/src/services/degreeService.js:26:51\n\n  23 };\n  24 exports.getDegreeById = getDegreeById;\n  25 const getDegrees = async () => {\n→ 26     const degrees = await client_1.default.degree.findMany(\nerror: Error validating datasource `db`: the URL must start with the protocol `postgresql://` or `postgres://`.\n  -->  schema.prisma:11\n   | \n10 |     provider          = \"postgresql\"\n11 |     url               = env(\"DATABASE_URL\")\n   | \n\nValidation Error Count: 1",

# Thoughts

It seems that the env variable for DATABASE_URL is not set correctly. We need to confirm how this is getting injected into the Digital Ocean environment and fix it.

**Comment by ermish** [comment]
this has been fixed moving to firebase
