### ISSUE TITLE
Create an `updateSubmission` method

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-server#220]
# Requirements

- [x] Create an `updateSubmission` method
- [ ] #296
    - [x] When a submission is approved, create a new facility and healthcareprofessionals from the submission data
        - [x] This should utilize the `add` methods in the corresponding `facilityService` and `healthcareProfessionalService` 
    - [x] When a submission is rejected, we don't delete it, just mark the flag `isRejected`. 
    - [ ] #297

**Comment by theyokohamalife** [comment]
From standup: Needs to call addFacility method and get the new facilityID. Then, use it in the Submission.

**Comment by theyokohamalife** [comment]
From standup: Will request early feedback on draft.
