### ISSUE TITLE
Pull all our docker commands in into yarn commands

### ISSUE THREAD

**Issue by theyokohamalife** [ourjapanlife/findadoc-server#232]
Consistency improvement: we could pull all our docker commands in into yarn commands so they're consistent and easy to find across multiple actions and usages.

_Originally posted by @ermish in https://github.com/ourjapanlife/findadoc-server/pull/227#discussion_r1306320207_

**Comment by ermish** [comment]
pair programmed with @theyokohamalife to update this in #227
