### ISSUE TITLE
Create a function to fetch PlaceID from Google Maps link

### ISSUE THREAD

**Issue by theyokohamalife** [ourjapanlife/findadoc-server#234]
Updated user flow:

The backend will have a mutation for updating the location and triggering the google search.
the front end will have a button on the moderator page to manually trigger the mutation
the front end can update the button to say something like "rerun" when the data already exists. (it can be rerun, but want to call out that it has already been run)
We don't want to auto-run because not all submissions will need it plus it will prevent costs on spam submissions

**Comment by theyokohamalife** [comment]
You can find a place ID by doing a ["Place Search"](https://developers.google.com/maps/documentation/places/web-service/search-find-place) request.

Examples

Query by radius for given coordinates:
```
https://maps.googleapis.com/maps/api/place/findplacefromtext/json
  ?fields=formatted_address%2Cname%2Crating%2Copening_hours%2Cgeometry
  &input=mongolian
  &inputtype=textquery
  &locationbias=circle%3A2000%4047.6918452%2C-122.2226413
  &key=YOUR_API_KEY
```

Query by phone number:

```
https://maps.googleapis.com/maps/api/place/findplacefromtext/json
  ?input=%2B16502530000
  &inputtype=phonenumber
  &key=YOUR_API_KEY
```

Query by name of place:

```
https://maps.googleapis.com/maps/api/place/findplacefromtext/json
  ?fields=formatted_address%2Cname%2Crating%2Copening_hours%2Cgeometry
  &input=Museum%20of%20Contemporary%20Art%20Australia
  &inputtype=textquery
  &key=YOUR_API_KEY
```

**Comment by ermish** [comment]
https://github.com/ourjapanlife/findadoc-server/pull/498#issuecomment-2388617987
added some new requirements. Will update the ticket
