### ISSUE TITLE
Create fake data

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-server#236]
# Requirements

- [ ] We want to be able to load up our mock firebase db with fake test data. 
- [ ] We want to be able to run tests and use fake data to save/retrieve. 
- [ ] This should be based on the gql types

**Comment by theyokohamalife** [comment]
@ermish We already have mocked data in place in the test suite using [addMocksToSchema](https://www.apollographql.com/docs/apollo-server/testing/mocking/) from `@graphql-tools/mocks` that can be saved/retrieved and is based on the gql types. It has the added benefit of not needing maintenance if the schema is updated. Is there a reason you feel this would be better? 
 
 Example: 

```
const mySchema = addMocksToSchema({
            schema,
            resolvers: store => ({
                Query: {
                    healthcareProfessional: (_, { id }) => store.get('HealthcareProfessional', id)
                }
            })
        })
```
