### ISSUE TITLE
Let's improve our readme!

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-server#245]
# Requirements

- [ ] Let's make our readme updated with our latest changes
   - [ ] Remove husky
   - [ ] Add details around local database setup
   - [ ] Explain how to debug code. 
   - [ ] Improve sections structuring

**Comment by theyokohamalife** [comment]
@ermish I know this is going to sound crazy, but I've actually grown a bit fond of Husky. It has prevent me and some of the other devs from committing changes that shouldn't be part of a PR.
