### ISSUE TITLE
Add Tests for submissionService functions

### ISSUE THREAD

**Issue by evan-desu** [ourjapanlife/findadoc-server#249]
- [x] Create **happy path** tests for the following:
   - [x] `getSubmissionById`
   - [x] `getSubmissions`
   - [x] `addSubmission`
   - [x] `updateSubmission`
- [x] Create **error path** tests for the following:
   - [x] `getSubmissionById`
   - [x] `addSubmission`
   - [x] `updateSubmission`
- [ ] Adding reset database for emulator

**Comment by theyokohamalife** [comment]
From standup: The resolvers didn't have try/catch, but that has been fixed and tests can be written for them.
