### ISSUE TITLE
Validate input fields for submission methods.

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-server#257]
# Summary

We need to validate the parameters that users are sending in. This should be for all queries and mutations. 
This ticket will focus on the submission based methods. 

# Requirements

- [x] Ensure the values sent in are valid.
    - [x] type checking should already be covered by graphql
- [x] ensure dynamic fields (like sort by - field name) matches valid options. Ex. can you sort by id? (we shouldn't) what about "abc"? (field doesn't exist)
- [x] Put limits on number fields. limit for example probably shouldn't go over 1000. if a user sends in -1 or 999999999, it should be invalid. 
- [x] Check for empty strings

### Specific to queries
- [ ] Check for malicious strings like js being injected as a string to be ran. (we can use a library, no pref)
- [x]  sort-by should be limited to two columns max.  (future ticket: we add this to our api documentation)

### Specific to Mutations

- [ ] Which fields should not be valid to add/update?
    - [ ] id, created date, and updated date are some examples that shouldn't be editable.

_Originally posted by @ermish in https://github.com/ourjapanlife/findadoc-server/pull/230#discussion_r1320758503_

**Comment by ermish** [comment]
updated the requirements @evan-desu

**Comment by Anissa3005** [comment]
@ermish @theyokohamalife This has also been implemented so can be closed as well
