### ISSUE TITLE
Create better seed data

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-server#271]
# Summary

When we load up the app locally, we should have nice seed data that lets us easily test any api query/mutation, and visualize how the web app would work in production. 

# Requirements

- [ ] Add better facilities seed data (at least 6-11)
- [ ] Add better healthcare providers seed data (a couple variations per facility)
- [ ] Add a few submissions in various states (approved, rejected, etc)

**Comment by theyokohamalife** [comment]
TODO: Get Excel list from LaShawn

**Comment by ermish** [comment]
@theyokohamalife bumping this up to high prioritiy as want to want to have quality, valid data when we launch MVP

**Comment by Anissa3005** [comment]
@ermish @theyokohamalife This issue can be closed I think, since we have seed data now?
