### ISSUE TITLE
test: Add Happy Path Tests for `getSubmissionById`

### ISSUE THREAD

**Issue by evan-desu** [ourjapanlife/findadoc-server#290]
# Summary

We need to add happy path tests for `getSubmissionById`.

# Requirements

- [x] Add tests checking every field in a submission!

# Dependencies

- None

**Comment by theyokohamalife** [comment]
This is almost completed. Just need doc strings added for `getSubmissionById`

**Comment by evan-desu** [comment]
@theyokohamalife Done!
