### ISSUE TITLE
Add a script to build the backend

### ISSUE THREAD

**Issue by ann-kilzer** [ourjapanlife/findadoc-server#38]
We don't have a proper `yarn build` script. 

Do we need to "build" the backend? What's the best way to get a node application running in production?

Relates to #28 

Consider reviewing: https://2022.stateofjs.com/en-US/libraries/build-tools/

**Comment by ermish** [comment]
I highly recommend checking out parcel! It's been by far easier and faster than webpack or roll up 👌

**Comment by ann-kilzer** [comment]
Updated ticket description to reflect recommendations from https://2022.stateofjs.com/en-US/libraries/build-tools/

**Comment by ermish** [comment]
I'm actually the most curious about turbopack. My vote is for us to try it and a monorepo style app ✨. 

I did some investigation of it and I think it's pretty low risk for us (even though it's alpha) and easy to switch away from if it's not working out

**Comment by ermish** [comment]
Is anyone planning on working on this? I'd love to take a shot at this, but don't want to take away a learning opportunity from someone else. 🙃 
@theyokohamalife @ann-kilzer

**Comment by ann-kilzer** [comment]
I'd like to do it if it's unclaimed, and really want to steer clear of any alpha or beta code. Bleeding edge tools are both volatile and have less community knowledge, and we need to treat this like a long term software project

**Comment by ann-kilzer** [comment]
@theyokohamalife and I are noticing that "build" might not make sense given this is a backend node app. I am looking into it as part of my work on #28

**Comment by ann-kilzer** [comment]
Let's hold off on this / make some major rethinking about what we need here. 

We need to optimize production runs.
There may be a benefit to pre building typescript

**Comment by theyokohamalife** [comment]
Currently having issues with node_modules. Probably one more week before it'll be ready to deploy to Digital Ocean. Original plan was 4 days.
