### ISSUE TITLE
Security review

### ISSUE THREAD

**Issue by ann-kilzer** [ourjapanlife/findadoc-server#46]
# To discuss:
- secret management
- separation of dev / prod
- access control
- PII removal requests
- repo privacy
- web security auditing
- OWASP Top 10 checks
- API parameter validation (ensure type checking and sql injection prevention)
- etc.

**Comment by ermish** [comment]
added API parameter validation (ensure type checking and sql injection prevention)

**Comment by ann-kilzer** [comment]
Switching from Dependabot to Mend Rennovate for security & package updates
