### ISSUE TITLE
Bug: Fix typescript type generator

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-server#60]
## Requirements

- typescript types and typescript enums should be generated from the gql -> typescript generator.

**Comment by ann-kilzer** [comment]
In #109 we're changing the generator to use the graphQL file rather than the server. Is there other work that needs to be done on this ticket? @ermish

**Comment by ermish** [comment]
Need to double check, but I think @theyokohamalife already fixed this. 
The typescript types were missing

**Comment by theyokohamalife** [comment]
This was fixed with #69
