### ISSUE TITLE
Move .sh scripts within a wrapper docker image

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-server#91]
# Requirements

- [ ] Create a wrapper docker image around postgress.
- [ ] Move the `.sh` scripts and the `command: "sh -c 'until [[ -f /in/db-init-done && -d /target/node_modules ]]; do sleep 1; done; yarn migrate; yarn prisma db seed'"` command into the container. 
- [ ] Optional: Could consolidate the db, db-configure, install-deps, and migrate steps into a `db` single docker image while we're at it. 

# Dependencies

- None

**Comment by ann-kilzer** [comment]
Can you clarify this ticket or do a little more research on which part is failing in Windows?

**Comment by ann-kilzer** [comment]
So just for clarity on this I added a `uname -A` into the shell script and got:
```sh
findadoc-server-db-configure-1  | Linux 0645469eb0fd 5.10.104-linuxkit #1 SMP Thu Mar 17 17:08:06 UTC 2022 x86_64 Linux
```

I don't think there's any reason for us to fear shell scripts in Docker

**Comment by ann-kilzer** [comment]
As discussed in slack, can we open a new "bug" issue if there are specific errors happening in Docker on Windows? Then we can have a clearer picture of what's a blocker vs. what's a stylistic change.

Removing bug and prioritization for these reasons.
