### ISSUE TITLE
Fix docker compose up to work on Windows

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-server#96]
# Requirements

- [ ] Fix it! Running `docker compose up` on windows fails (will add specific error later)

# Dependencies

- None

**Comment by ann-kilzer** [comment]
Setting up parallels and docker
https://zitseng.com/archives/10861#:~:text=Installation%20Steps%201%20%231%20%E2%80%93%20Install%20Docker%20Download,Parallels%20Desktop%20...%204%20%234%3A%20Hello-World%20Test%20

**Comment by ann-kilzer** [comment]
Oh nooooo
```
└ ➜ docker-machine create --driver=parallels default
Creating CA: /Users/annkilzer/.docker/machine/certs/ca.pem
Creating client certificate: /Users/annkilzer/.docker/machine/certs/cert.pem
Running pre-create checks...
Error with pre-create check: "Docker Machine can be used only with Parallels Desktop Pro or Business edition. You use: standard edition"
```

**Comment by ann-kilzer** [comment]
I requested a refund for parallels and will be refunding the money to the grant account. I don't have the bandwidth to work on this issue further. Someone else is welcome to take it

**Comment by ermish** [comment]
this is fixed!
